spring.application.name=desafio
spring.datasource.url=jdbc:h2:mem:proposals;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=false
spring.jackson.default-property-inclusion=non_null
